### PR TITLE
Removes detection criteria that failed if vendor directory was present

### LINKED ISSUE #173: Buildpack should run to set BP_GO_VERSION for go-dist buildpack
## What happened?

* What were you attempting to do?

Trying to build a go app that has vendored dependencies with go 1.16. The `go.mod` file has:
```
go 1.16
```

* What did you expect to happen?

This should build the app image with go 1.16

* What was the actual behavior? Please provide log output, if possible.

This buildpack failed to detect and the go-dist buildpack expected either `BP_GO_VERSION` to be set in the environment or through the `buildpack.yml` (which is deprecated.) This means that a user needs to specify the version of go in an additional location than just using the `go.mod` file to verify the version required.

```
===> BUILDING
[builder] Paketo Go Distribution Buildpack 0.3.0
[builder]   Resolving Go version
[builder]     Candidate version sources (in priority order):
[builder]       <unknown> -> ""
[builder]
[builder]     Selected Go version (using <unknown>): 1.15.8
[builder]
[builder]   Reusing cached layer /layers/paketo-buildpacks_go-dist/go
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

pack latest cli

* What buildpacks are you using? Please include versions.

go buildpack v0.4.0

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

custom but not relevant

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

no buildpack config

## Checklist

* [x] I have included log output.
* [ ] The log output includes an error message.
* [x] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by ryanmoran**
## Summary

Since we might have a vendor directory and still want to specify the version that comes from the `go.mod` file, we should still detect.

Resolves #173 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have added an integration test, if necessary.

### CODE REVIEW

**Review by genevieve — APPROVED** [review]

**Review by ForestEckhardt — CHANGES_REQUESTED** [review]
I am running into problems when I try and run this buildpack in an offline environment now. `go mod` always tries reaching out to the internet, meaning if there is no internet connection then the commands fail and so does the build phase. I think that the idea of the `go.mod` file always influencing the version selection process is sound but I think we need to find another way of going at it.

**Comment by ryanmoran** [comment]
All the tests are passing. Maybe we should also add an offline test for this buildpack?

**Comment by ForestEckhardt** [comment]
I definitely think we the reason we didn't previously have one is that this buildpack would not detect if the app was offline capable. Are you proposing that the app should pass detection in situations where the buildpacks appears to be vendored?

**Comment by ryanmoran** [comment]
Yeah. I think it should still detect, but only to influence the version of Go to install based on what is present in the `go.mod` file. I will need to add some code into build that skips running the build process if the `vendor` directory is present.

**Comment by ForestEckhardt** [comment]
Yeah. I will go some benchmarking to see how much overhead even spinning up the `go-build` build process adds to the overall lifecycle build process.

**Comment by ryanmoran** [comment]
I've added a check for a `vendor` directory that will skip the build process when it is present. I've also included an offline test that confirms this works when the `vendor` directory is present.

**Comment by ForestEckhardt** [comment]
I did some very lazy bench marking and running the build process adds a negligible amount of time to the build time (~ 1 second) so this looks good to me.

**Review by ForestEckhardt — APPROVED** [review]

**Pull request merged**
